"use strict";
let DB={updated:"",items:[],stats:{total:0,missing:0,multi:0}};
const $=id=>document.getElementById(id);
const norm=s=>(s||"").toString().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let missing=[],multi=[],mode="search",lastResults=[];
function warehouseCode(v){const m=(v.sheet||"").match(/^([A-Z]+\d+)_/i);return m?m[1].toUpperCase():(v.warehouse||"Kho");}
function warehouseName(v){return v.warehouse||warehouseCode(v);}
function locText(v){
  const wh=esc(warehouseName(v));
  if((v.rack||"").toLowerCase().includes("mat_dat")||(v.rack||"").toLowerCase().includes("mặt đất")) return `📍 ${wh} • Mặt đất • Khoang ${esc(v.compartment)}`;
  return `📍 ${wh} • Giá ${esc(v.rack)} • Tầng ${esc(v.level)} • Khoang ${esc(v.compartment)}`;
}
function summaryCard(x){return `<div class="summary"><div><div class="label">Mã vật tư</div><div class="value">${esc(x.code)}</div></div><div><div class="label">Tên vật tư</div><div class="value">${esc(x.name)}</div></div><div><div class="label">Đơn vị tính</div><div class="value">${esc(x.unit)}</div></div><div><div class="label">Tồn hệ thống</div><div class="value stock">${esc(x.stock)}</div></div></div>`;}
function itemCard(x){const loc=x.locations.length?`<div class="section-head">Vị trí đang lưu (${x.locations.length})</div>${x.locations.map(v=>`<div class="location-card ${x.locations.length>1?"multi":""}"><div class="loc-main">${locText(v)}</div><span class="badge">Đang có</span></div>`).join("")}`:`<div class="location-card multi"><div class="loc-main">Chưa có vị trí</div></div>`;return `<article>${summaryCard(x)}${loc}</article>`;}
function smallCard(x){return `<div class="item-card"><div class="item-top"><div><div class="code">${esc(x.code)}</div><div class="name">${esc(x.name)}</div></div><b>${x.locations.length?x.locations.length+" vị trí":"Tồn: "+esc(x.stock)}</b></div><div class="meta">ĐVT: ${esc(x.unit)} • Tồn hệ thống: ${esc(x.stock)}</div>${x.locations.map(v=>`<div class="meta">${locText(v)}</div>`).join("")}</div>`;}
function setActive(m){mode=m;document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));}
function renderSearch(arr){$("searchCount").textContent=arr.length?`(${arr.length})`:"";if(!arr.length){$("content").innerHTML='<div class="empty">Nhập mã hoặc tên vật tư để tra cứu.</div>';return;}$("content").innerHTML=`<div class="result-count">Tìm thấy ${arr.length} kết quả</div>${arr.map(itemCard).join("")}`;}
function renderList(arr,title){$("content").innerHTML=`<div class="section-head">${title} (${arr.length})</div><div class="item-list">${arr.map(smallCard).join("")}</div>`;}
function doSearch(){const q=norm($("q").value);const t=document.querySelector('input[name="searchType"]:checked').value;if(!q){lastResults=[];renderSearch([]);return;}lastResults=DB.items.filter(x=>t==="code"?norm(x.code).includes(q):t==="name"?norm(x.name).includes(q):norm(x.code).includes(q)||norm(x.name).includes(q));setActive("search");renderSearch(lastResults);}
function showMode(m){setActive(m);if(m==="missing")renderList(missing,"Vật tư có tồn nhưng chưa có vị trí");else if(m==="multi")renderList(multi,"Vật tư đang có nhiều vị trí");else if(m==="rack")document.querySelector(".rack-panel").scrollIntoView({behavior:"smooth"});else renderSearch(lastResults);}
function initRack(){const warehouses=new Map();DB.items.forEach(x=>x.locations.forEach(v=>{const key=warehouseCode(v);if(!warehouses.has(key))warehouses.set(key,warehouseName(v));}));$("warehouseSelect").innerHTML=[...warehouses].map(([k,n])=>`<option value="${esc(k)}">${esc(n)}</option>`).join("");updateRackOptions();}
function updateRackOptions(){const w=$("warehouseSelect").value;const racks=new Set();DB.items.forEach(x=>x.locations.forEach(v=>{if(warehouseCode(v)===w)racks.add(v.rack);}));$("rackSelect").innerHTML=[...racks].sort().map(r=>`<option value="${esc(r)}">${String(r).toLowerCase().includes("mat_dat")?"Mặt đất":"Giá "+esc(r)}</option>`).join("");renderRack();}
function renderRack(){const w=$("warehouseSelect").value,r=$("rackSelect").value;const rows=[];DB.items.forEach(x=>x.locations.forEach(v=>{if(warehouseCode(v)===w&&v.rack===r)rows.push({x,v});}));const wh=rows[0]?warehouseName(rows[0].v):w;const levels={};rows.forEach(o=>{const key=(String(r).toLowerCase().includes("mat_dat")?"Mặt đất":`Tầng ${o.v.level}`)+` • Khoang ${o.v.compartment}`;(levels[key]??=[]).push(o.x);});$("rackSummary").innerHTML=`<b>📍 ${esc(wh)} • ${String(r).toLowerCase().includes("mat_dat")?"Mặt đất":"Giá "+esc(r)}</b>Tổng số mã vật tư: ${new Set(rows.map(o=>o.x.code)).size}`;$("groups").innerHTML=Object.entries(levels).map(([k,a])=>`<div class="group"><h3>${esc(k)} (${a.length})</h3>${a.map(x=>`<div class="rack-row"><b>${esc(x.code)}</b><span>${esc(x.name)}</span><span class="qty">${esc(x.stock)} ${esc(x.unit)}</span></div>`).join("")}</div>`).join("")||'<div class="empty">Không có vật tư.</div>';}
function bindEvents(){document.querySelectorAll("[data-mode]").forEach(b=>b.addEventListener("click",()=>showMode(b.dataset.mode)));$("btnSearch").onclick=doSearch;$("btnClear").onclick=()=>{$("q").value="";lastResults=[];showMode("search");};$("q").addEventListener("keydown",e=>{if(e.key==="Enter")doSearch();});$("warehouseSelect").onchange=updateRackOptions;$("rackSelect").onchange=renderRack;}
async function loadData(){try{const response=await fetch(`data.json?t=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);DB=await response.json();if(!DB||!Array.isArray(DB.items))throw new Error("Dữ liệu không đúng cấu trúc");missing=DB.items.filter(x=>Number(x.stock)>0&&x.locations.length===0);multi=DB.items.filter(x=>x.locations.length>=2);$("updated").textContent=DB.updated||"Không rõ";$("missingCount").textContent=missing.length;$("multiCount").textContent=multi.length;$("dataStatus").textContent=`Đã tải ${DB.items.length} mã vật tư`;initRack();renderSearch([]);}catch(err){console.error(err);$("dataStatus").textContent="Không tải được dữ liệu";$("content").innerHTML=`<div class="error-box"><b>Không tải được data.json.</b><br>Hãy kiểm tra file data.json đã được tải lên GitHub cùng thư mục với index.html chưa.<br><small>${esc(err.message)}</small></div>`;}}
bindEvents();loadData();
